### ISSUE TITLE
[Feature]: Loongarch架构支持

### ISSUE THREAD

**Issue by Lichenkass** [pot-app/pot-desktop#644]
### Description

龙芯3A6000已发布，希望支持Loongarch架构

### Application Scenario

龙芯新旧世界架构支持

**Comment by Pylogmon** [comment]
交叉编译比较麻烦，也不知道依赖是不是都支持loongarch，你要有设备的话先直接编译尝试一下。

**Comment by Integral-Tech** [comment]
Debian 上游尚未完全支持 Loongarch（ Debian 对 LoongArch 的适配情况：https://areweloongyet.com/project/debian ）

**Comment by Lichenkass** [comment]
https://github.com/pot-app/pot-desktop/issues/644#issuecomment-1871315391
编译报错，未支持的架构

**Comment by LichenKassYuan** [comment]
@Pylogmon 编译报错
```
> pot@2.7.9 tauri /home/Yuan0866/Downloads/pot-desktop
> tauri "build"

/home/Yuan0866/Downloads/pot-desktop/node_modules/.pnpm/@tauri-apps+cli@1.5.10/node_modules/@tauri-apps/cli/index.js:241
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
        ^

Error: Unsupported architecture on Linux: loong64
    at Object.<anonymous> (/home/Yuan0866/Downloads/pot-desktop/node_modules/.pnpm/@tauri-apps+cli@1.5.10/node_modules/@tauri-apps/cli/index.js:241:15)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)
    at Module.load (node:internal/modules/cjs/loader:1197:32)
    at Module._load (node:internal/modules/cjs/loader:1013:12)
    at Module.require (node:internal/modules/cjs/loader:1225:19)
    at require (node:internal/modules/helpers:177:18)
    at Object.<anonymous> (/home/Yuan0866/Downloads/pot-desktop/node_modules/.pnpm/@tauri-apps+cli@1.5.10/node_modules/@tauri-apps/cli/main.js:5:27)
    at Module._compile (node:internal/modules/cjs/loader:1356:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1414:10)

Node.js v18.19.0
 ELIFECYCLE  Command failed with exit code 1.
```
